server:
  servlet:
    context-path: /sunny-web
    port: 8080

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/sunny?characterEncoding=utf8
        username: root
        password: s@123456
      # 从库数据源
      slave:
        url: jdbc:mysql://localhost:3306/sunny?characterEncoding=utf8
        username: root
        password: s@123456
      # 初始连接数
      initial-size: 10
      # 最大连接池数量
      max-active: 100
      # 最小连接池数量
      min-idle: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /monitor/druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

# MyBatis
mybatis:
  #sql打印配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

my:
  value: 100

#spring:
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    check-template-location: true
#    suffix: .html
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    mode: HTML
#
###数据库连接配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sunny?characterEncoding=UTF-8
#    username: root
#    password: s@123456
#    type: com.alibaba.druid.pool.DruidDataSource
#
###mybatis配置
#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml

